// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/pix/v1/pix.proto

package pix

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PixType int32

const (
	PixType_EMAIL  PixType = 0
	PixType_PHONE  PixType = 1
	PixType_CPF    PixType = 2
	PixType_RANDOM PixType = 3
)

var PixType_name = map[int32]string{
	0: "EMAIL",
	1: "PHONE",
	2: "CPF",
	3: "RANDOM",
}

var PixType_value = map[string]int32{
	"EMAIL":  0,
	"PHONE":  1,
	"CPF":    2,
	"RANDOM": 3,
}

func (x PixType) String() string {
	return proto.EnumName(PixType_name, int32(x))
}

func (PixType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5bffb3d7d701b3b, []int{0}
}

type BankAccount struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BankCode             string   `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	BankName             string   `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankBranch           string   `protobuf:"bytes,4,opt,name=bank_branch,json=bankBranch,proto3" json:"bank_branch,omitempty"`
	AccountNumber        string   `protobuf:"bytes,5,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankAccount) Reset()         { *m = BankAccount{} }
func (m *BankAccount) String() string { return proto.CompactTextString(m) }
func (*BankAccount) ProtoMessage()    {}
func (*BankAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5bffb3d7d701b3b, []int{0}
}

func (m *BankAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankAccount.Unmarshal(m, b)
}
func (m *BankAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankAccount.Marshal(b, m, deterministic)
}
func (m *BankAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankAccount.Merge(m, src)
}
func (m *BankAccount) XXX_Size() int {
	return xxx_messageInfo_BankAccount.Size(m)
}
func (m *BankAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BankAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BankAccount proto.InternalMessageInfo

func (m *BankAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BankAccount) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *BankAccount) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *BankAccount) GetBankBranch() string {
	if m != nil {
		return m.BankBranch
	}
	return ""
}

func (m *BankAccount) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type Pix struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BankAccountId        string   `protobuf:"bytes,3,opt,name=bank_account_id,json=bankAccountId,proto3" json:"bank_account_id,omitempty"`
	Balance              string   `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pix) Reset()         { *m = Pix{} }
func (m *Pix) String() string { return proto.CompactTextString(m) }
func (*Pix) ProtoMessage()    {}
func (*Pix) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5bffb3d7d701b3b, []int{1}
}

func (m *Pix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pix.Unmarshal(m, b)
}
func (m *Pix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pix.Marshal(b, m, deterministic)
}
func (m *Pix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pix.Merge(m, src)
}
func (m *Pix) XXX_Size() int {
	return xxx_messageInfo_Pix.Size(m)
}
func (m *Pix) XXX_DiscardUnknown() {
	xxx_messageInfo_Pix.DiscardUnknown(m)
}

var xxx_messageInfo_Pix proto.InternalMessageInfo

func (m *Pix) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pix) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Pix) GetBankAccountId() string {
	if m != nil {
		return m.BankAccountId
	}
	return ""
}

func (m *Pix) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type PixCode struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PixId                string   `protobuf:"bytes,2,opt,name=pix_id,json=pixId,proto3" json:"pix_id,omitempty"`
	Type                 PixType  `protobuf:"varint,3,opt,name=type,proto3,enum=mentoria.pix.v1.PixType" json:"type,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixCode) Reset()         { *m = PixCode{} }
func (m *PixCode) String() string { return proto.CompactTextString(m) }
func (*PixCode) ProtoMessage()    {}
func (*PixCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5bffb3d7d701b3b, []int{2}
}

func (m *PixCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixCode.Unmarshal(m, b)
}
func (m *PixCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixCode.Marshal(b, m, deterministic)
}
func (m *PixCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixCode.Merge(m, src)
}
func (m *PixCode) XXX_Size() int {
	return xxx_messageInfo_PixCode.Size(m)
}
func (m *PixCode) XXX_DiscardUnknown() {
	xxx_messageInfo_PixCode.DiscardUnknown(m)
}

var xxx_messageInfo_PixCode proto.InternalMessageInfo

func (m *PixCode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PixCode) GetPixId() string {
	if m != nil {
		return m.PixId
	}
	return ""
}

func (m *PixCode) GetType() PixType {
	if m != nil {
		return m.Type
	}
	return PixType_EMAIL
}

func (m *PixCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SenderId             string   `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId           string   `protobuf:"bytes,5,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5bffb3d7d701b3b, []int{3}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Transaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Transaction) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *Transaction) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

type ListUserTransactionsByIdResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUserTransactionsByIdResponse) Reset()         { *m = ListUserTransactionsByIdResponse{} }
func (m *ListUserTransactionsByIdResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserTransactionsByIdResponse) ProtoMessage()    {}
func (*ListUserTransactionsByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5bffb3d7d701b3b, []int{4}
}

func (m *ListUserTransactionsByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserTransactionsByIdResponse.Unmarshal(m, b)
}
func (m *ListUserTransactionsByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserTransactionsByIdResponse.Marshal(b, m, deterministic)
}
func (m *ListUserTransactionsByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserTransactionsByIdResponse.Merge(m, src)
}
func (m *ListUserTransactionsByIdResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserTransactionsByIdResponse.Size(m)
}
func (m *ListUserTransactionsByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserTransactionsByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserTransactionsByIdResponse proto.InternalMessageInfo

func (m *ListUserTransactionsByIdResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterEnum("mentoria.pix.v1.PixType", PixType_name, PixType_value)
	proto.RegisterType((*BankAccount)(nil), "mentoria.pix.v1.BankAccount")
	proto.RegisterType((*Pix)(nil), "mentoria.pix.v1.Pix")
	proto.RegisterType((*PixCode)(nil), "mentoria.pix.v1.PixCode")
	proto.RegisterType((*Transaction)(nil), "mentoria.pix.v1.Transaction")
	proto.RegisterType((*ListUserTransactionsByIdResponse)(nil), "mentoria.pix.v1.ListUserTransactionsByIdResponse")
}

func init() { proto.RegisterFile("protobuf/pix/v1/pix.proto", fileDescriptor_c5bffb3d7d701b3b) }

var fileDescriptor_c5bffb3d7d701b3b = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x4e, 0xdb, 0x40,
	0x10, 0x75, 0x2e, 0x24, 0x64, 0xd2, 0x40, 0xd8, 0x16, 0xea, 0x86, 0x4a, 0x45, 0x96, 0x5a, 0xa1,
	0xaa, 0x32, 0x82, 0xf6, 0xa5, 0xed, 0x0b, 0x24, 0xa4, 0x60, 0x09, 0x82, 0x9b, 0xc2, 0x4b, 0x5f,
	0xd0, 0xda, 0x3b, 0xa5, 0x2b, 0xf0, 0x45, 0xb6, 0x13, 0x39, 0x5f, 0xd0, 0xcf, 0xe8, 0x17, 0xf6,
	0x1f, 0xaa, 0xdd, 0x75, 0x12, 0x97, 0x70, 0x6d, 0x9e, 0xbc, 0x7b, 0xce, 0xec, 0xcc, 0x99, 0xd9,
	0xd9, 0x31, 0xbc, 0x08, 0xa3, 0x20, 0x09, 0x9c, 0xc1, 0x8f, 0xad, 0x90, 0xa7, 0x5b, 0xc3, 0x6d,
	0xf1, 0x31, 0x25, 0x46, 0x96, 0x3d, 0xf4, 0x93, 0x20, 0xe2, 0xd4, 0x14, 0xd8, 0x70, 0xbb, 0xb5,
	0x7e, 0x11, 0x04, 0x17, 0x57, 0xb8, 0x35, 0x39, 0x82, 0x5e, 0x98, 0x8c, 0x94, 0xb5, 0xf1, 0xbb,
	0x00, 0xf5, 0x36, 0xf5, 0x2f, 0xf7, 0x5c, 0x37, 0x18, 0xf8, 0x09, 0x59, 0x82, 0x22, 0x67, 0x7a,
	0x61, 0xa3, 0xb0, 0x59, 0xeb, 0x17, 0x39, 0x23, 0xeb, 0x50, 0x73, 0xa8, 0x7f, 0x79, 0xee, 0x06,
	0x0c, 0xf5, 0xa2, 0x84, 0x17, 0x05, 0xd0, 0x09, 0x18, 0x4e, 0x48, 0x9f, 0x7a, 0xa8, 0x97, 0xa6,
	0x64, 0x8f, 0x7a, 0x48, 0x5e, 0x41, 0x5d, 0x92, 0x4e, 0x44, 0x7d, 0xf7, 0xa7, 0x5e, 0x96, 0x34,
	0x08, 0xa8, 0x2d, 0x11, 0xf2, 0x1a, 0x96, 0xa8, 0x8a, 0x7a, 0xee, 0x0f, 0x3c, 0x07, 0x23, 0x7d,
	0x41, 0xda, 0x34, 0x32, 0xb4, 0x27, 0x41, 0x23, 0x84, 0x92, 0xcd, 0xd3, 0x19, 0x61, 0xcf, 0xa1,
	0x3a, 0x88, 0x31, 0x3a, 0xe7, 0x2c, 0x93, 0x55, 0x11, 0x5b, 0x8b, 0x91, 0x37, 0xb0, 0x2c, 0xe3,
	0x8e, 0x7d, 0x73, 0x96, 0x49, 0x6b, 0x38, 0xd3, 0x3c, 0x2d, 0x46, 0x74, 0xa8, 0x3a, 0xf4, 0x8a,
	0xfa, 0x2e, 0x66, 0xda, 0xc6, 0x5b, 0x23, 0x82, 0xaa, 0xcd, 0x53, 0x99, 0xe1, 0xf5, 0xa8, 0xab,
	0x50, 0x09, 0x79, 0x3a, 0x0d, 0xba, 0x10, 0xf2, 0xd4, 0x62, 0xe4, 0x1d, 0x94, 0x93, 0x51, 0xa8,
	0x6a, 0xb0, 0xb4, 0xa3, 0x9b, 0xd7, 0xae, 0xc0, 0xb4, 0x79, 0x7a, 0x3a, 0x0a, 0xb1, 0x2f, 0xad,
	0x08, 0x81, 0xb2, 0x2c, 0xa7, 0x0a, 0x2b, 0xd7, 0xc6, 0xaf, 0x02, 0xd4, 0x4f, 0x23, 0xea, 0xc7,
	0xd4, 0x4d, 0x78, 0xe0, 0xcf, 0x04, 0x26, 0x50, 0x66, 0x34, 0x19, 0x5f, 0x81, 0x5c, 0x93, 0x35,
	0xa8, 0x50, 0x4f, 0x64, 0x93, 0x25, 0x98, 0xed, 0xc4, 0xb5, 0xc4, 0xe8, 0x33, 0x55, 0x1c, 0x15,
	0x64, 0x51, 0x01, 0x16, 0x13, 0xd7, 0x12, 0xa1, 0x8b, 0x7c, 0xa8, 0x68, 0x55, 0x72, 0x18, 0x43,
	0x16, 0x33, 0x18, 0x6c, 0x1c, 0xf1, 0x38, 0x39, 0x8b, 0x31, 0xca, 0x09, 0x8a, 0xdb, 0x23, 0x8b,
	0xf5, 0x31, 0x0e, 0x03, 0x3f, 0x46, 0xb2, 0x0b, 0x4f, 0x92, 0x1c, 0xa7, 0x17, 0x36, 0x4a, 0x9b,
	0xf5, 0x9d, 0x97, 0x33, 0x79, 0xe7, 0x1c, 0xf4, 0xff, 0x39, 0xf1, 0xf6, 0x83, 0xac, 0xb1, 0x28,
	0x0a, 0xa9, 0xc1, 0x42, 0xf7, 0x78, 0xcf, 0x3a, 0x6a, 0x6a, 0x62, 0x69, 0x1f, 0x9e, 0xf4, 0xba,
	0xcd, 0x02, 0xa9, 0x42, 0xa9, 0x63, 0x7f, 0x69, 0x16, 0x09, 0x40, 0xa5, 0xbf, 0xd7, 0xdb, 0x3f,
	0x39, 0x6e, 0x96, 0x76, 0xfe, 0x54, 0x01, 0x6c, 0x9e, 0x7e, 0xc3, 0x68, 0xc8, 0x5d, 0x24, 0x5f,
	0x61, 0xa5, 0x13, 0x21, 0x4d, 0x30, 0xdf, 0xc1, 0xb3, 0x2a, 0x72, 0x6c, 0xeb, 0x4e, 0xd6, 0xd0,
	0x48, 0x1f, 0xc8, 0x01, 0x26, 0x39, 0x4c, 0xe4, 0x3d, 0xa7, 0xcf, 0x8f, 0x50, 0x53, 0x32, 0x45,
	0x1f, 0x3f, 0xbb, 0xa9, 0x39, 0x5a, 0x37, 0xa2, 0x86, 0x46, 0x3e, 0x01, 0x1c, 0x60, 0x62, 0xf3,
	0x54, 0xca, 0x78, 0xdc, 0xd9, 0x5d, 0x68, 0x9e, 0x85, 0x4c, 0x85, 0x6d, 0xab, 0xd6, 0x7e, 0xa4,
	0x87, 0x2e, 0x34, 0x26, 0xc2, 0xe5, 0x73, 0xb8, 0xb1, 0xb3, 0x05, 0xd3, 0xba, 0x95, 0x31, 0x34,
	0x62, 0xc1, 0x8a, 0x4a, 0x42, 0xec, 0xdb, 0x23, 0x5b, 0x3e, 0x99, 0xff, 0x73, 0x75, 0x08, 0xcd,
	0xbc, 0xab, 0x39, 0x44, 0x75, 0xa1, 0x31, 0xa9, 0xce, 0x1c, 0x6e, 0x3a, 0xd0, 0xd8, 0xc7, 0x2b,
	0x7c, 0x88, 0x9b, 0x35, 0x53, 0x0d, 0x62, 0x73, 0x3c, 0x88, 0xcd, 0xae, 0x18, 0xc4, 0x86, 0x36,
	0xed, 0xe3, 0xfc, 0x04, 0xb8, 0xf3, 0x35, 0xb5, 0xee, 0x64, 0x0d, 0x8d, 0x78, 0xa0, 0xdf, 0xf6,
	0x8a, 0xef, 0xf1, 0xbc, 0x3d, 0xc3, 0xde, 0x37, 0x0e, 0x0c, 0x8d, 0x9c, 0xc1, 0xaa, 0xaa, 0x66,
	0xce, 0xe6, 0x01, 0xb1, 0xee, 0xc9, 0xa2, 0xbd, 0xfa, 0xfd, 0xe9, 0xd8, 0x20, 0xfb, 0xd1, 0x7d,
	0x0e, 0x79, 0xea, 0x54, 0x64, 0x05, 0xdf, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x71, 0x77, 0x8d,
	0xd3, 0x06, 0x07, 0x00, 0x00,
}
