// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/user/v1/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Contact struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d0d105e971208f, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	SocialName           string   `protobuf:"bytes,3,opt,name=social_name,json=socialName,proto3" json:"social_name,omitempty"`
	Cpf                  string   `protobuf:"bytes,4,opt,name=cpf,proto3" json:"cpf,omitempty"`
	ContactId            string   `protobuf:"bytes,5,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d0d105e971208f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetSocialName() string {
	if m != nil {
		return m.SocialName
	}
	return ""
}

func (m *User) GetCpf() string {
	if m != nil {
		return m.Cpf
	}
	return ""
}

func (m *User) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type GetContactByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactByIdRequest) Reset()         { *m = GetContactByIdRequest{} }
func (m *GetContactByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactByIdRequest) ProtoMessage()    {}
func (*GetContactByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d0d105e971208f, []int{2}
}

func (m *GetContactByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactByIdRequest.Unmarshal(m, b)
}
func (m *GetContactByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetContactByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactByIdRequest.Merge(m, src)
}
func (m *GetContactByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactByIdRequest.Size(m)
}
func (m *GetContactByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactByIdRequest proto.InternalMessageInfo

func (m *GetContactByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d0d105e971208f, []int{3}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d0d105e971208f, []int{4}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*Contact)(nil), "mentoria.user.v1.Contact")
	proto.RegisterType((*User)(nil), "mentoria.user.v1.User")
	proto.RegisterType((*GetContactByIdRequest)(nil), "mentoria.user.v1.GetContactByIdRequest")
	proto.RegisterType((*GetUserByIdRequest)(nil), "mentoria.user.v1.GetUserByIdRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "mentoria.user.v1.ListUsersResponse")
}

func init() { proto.RegisterFile("protobuf/user/v1/user.proto", fileDescriptor_b0d0d105e971208f) }

var fileDescriptor_b0d0d105e971208f = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x14, 0xa4, 0x7c, 0xa8, 0x7d, 0x55, 0x02, 0x1b, 0xd1, 0x0a, 0x31, 0x62, 0x25, 0x81, 0x83, 0x29,
	0x01, 0x8f, 0x26, 0x26, 0xc2, 0x81, 0xe0, 0x07, 0x87, 0x1a, 0x3c, 0x78, 0x21, 0xa5, 0x7d, 0xc4,
	0x4d, 0xe8, 0x87, 0xdd, 0x96, 0xc4, 0x1f, 0xe0, 0x9f, 0xf0, 0xd7, 0x9a, 0x6e, 0x0b, 0x2a, 0xa5,
	0x24, 0x7a, 0x2a, 0x3b, 0x33, 0x4c, 0x66, 0xde, 0xdb, 0x85, 0x9a, 0xeb, 0x39, 0xbe, 0x33, 0x0d,
	0x66, 0xed, 0x80, 0xa1, 0xd7, 0x5e, 0x74, 0xf8, 0x57, 0xe5, 0x28, 0x29, 0x59, 0x68, 0xfb, 0x8e,
	0x47, 0x75, 0x95, 0x83, 0x8b, 0x8e, 0xa2, 0xc1, 0x6e, 0xdf, 0xb1, 0x7d, 0xdd, 0xf0, 0x49, 0x11,
	0xb2, 0xd4, 0x94, 0x85, 0xba, 0xd0, 0x12, 0xb5, 0x2c, 0x35, 0xc9, 0x21, 0x14, 0xd0, 0xd2, 0xe9,
	0x5c, 0xce, 0x72, 0x28, 0x3a, 0x90, 0x73, 0xd8, 0x77, 0x5f, 0x1d, 0x1b, 0x27, 0x76, 0x60, 0x4d,
	0xd1, 0x93, 0x73, 0x9c, 0x94, 0x38, 0x36, 0xe2, 0x90, 0xf2, 0x21, 0x40, 0x7e, 0xcc, 0xd0, 0x4b,
	0x38, 0xd6, 0x40, 0x9c, 0x05, 0xf3, 0xf9, 0xc4, 0xd6, 0x2d, 0x8c, 0x5d, 0xf7, 0x42, 0x60, 0xa4,
	0x5b, 0x48, 0xce, 0x40, 0x62, 0x8e, 0x41, 0xf5, 0x98, 0x8e, 0x7c, 0x21, 0x82, 0xb8, 0xa0, 0x04,
	0x39, 0xc3, 0x9d, 0xc9, 0x79, 0x4e, 0x84, 0x3f, 0xc9, 0x29, 0x80, 0x11, 0x85, 0x9f, 0x50, 0x53,
	0x2e, 0x70, 0x42, 0x8c, 0x91, 0xa1, 0xa9, 0x34, 0xa1, 0x32, 0x40, 0x3f, 0xae, 0xd7, 0x7b, 0x1f,
	0x9a, 0x1a, 0xbe, 0x05, 0xc8, 0x12, 0x4d, 0x95, 0x06, 0x90, 0x01, 0xfa, 0x61, 0xe4, 0x6d, 0xaa,
	0x5b, 0x28, 0x3f, 0x50, 0xc6, 0x65, 0x4c, 0x43, 0xe6, 0x3a, 0x36, 0x43, 0x72, 0x09, 0x85, 0x70,
	0x94, 0x4c, 0x16, 0xea, 0xb9, 0x96, 0xd4, 0x3d, 0x52, 0xd7, 0x27, 0xac, 0x86, 0x7a, 0x2d, 0x12,
	0x75, 0x3f, 0xf3, 0x20, 0x85, 0xe7, 0x27, 0xf4, 0x16, 0xd4, 0x40, 0x32, 0x80, 0x83, 0xbe, 0x87,
	0xba, 0x8f, 0xcb, 0x1d, 0x9c, 0x24, 0xff, 0x1f, 0x53, 0xd5, 0x74, 0x4a, 0xc9, 0x90, 0x67, 0x28,
	0xfe, 0xae, 0x4a, 0x9a, 0x49, 0xf9, 0xc6, 0x61, 0x6c, 0xf7, 0xbd, 0x87, 0xf2, 0xd8, 0x35, 0xbf,
	0x03, 0x72, 0xeb, 0xff, 0x86, 0xbc, 0x01, 0x88, 0xda, 0xf2, 0xcb, 0x91, 0x32, 0xaa, 0x6a, 0x0a,
	0xae, 0x64, 0xc8, 0x23, 0x48, 0x3f, 0xd6, 0x44, 0x1a, 0x1b, 0x1b, 0xae, 0x6d, 0x71, 0x8b, 0xdd,
	0x1d, 0x88, 0xab, 0x7d, 0xa6, 0xa6, 0xb9, 0x48, 0xe2, 0x89, 0x4b, 0xa0, 0x64, 0x48, 0x0f, 0x8a,
	0xd1, 0x9c, 0x56, 0xe9, 0xfe, 0x5c, 0xaf, 0x77, 0xfc, 0x52, 0x59, 0x52, 0xcb, 0xb7, 0x7b, 0x1d,
	0x7e, 0xa7, 0x3b, 0xfc, 0xf1, 0x5e, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x14, 0x1b, 0x3c, 0xfd,
	0xdb, 0x03, 0x00, 0x00,
}
